# Generated by Django 2.2.5 on 2019-10-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_nodes', models.IntegerField()),
                ('start_ip', models.CharField(max_length=39)),
                ('end_ip', models.CharField(max_length=39)),
                ('start_port', models.IntegerField(blank=True)),
                ('end_port', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(choices=[('ALIVE', 'Is-Alive'), ('FULLTCP', 'Full TCP connect'), ('TCPSYN', 'TCP SYN'), ('TCPFIN', 'TCP FIN')], max_length=7)),
                ('scan_order', models.CharField(choices=[('SEQ', 'Sequential'), ('RAND', 'Random')], default='SEQ', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_port', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_by', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='starboardscanner_app.Report')),
            ],
        ),
    ]
