# Generated by Django 2.2.5 on 2019-10-06 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.TextField()),
            ],
        ),
    ]
