# Generated by Django 2.2.5 on 2019-10-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starboardscanner_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='result',
            new_name='location_status',
        ),
    ]
