# Generated by Django 2.2.5 on 2019-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starboardscanner_app', '0002_auto_20191008_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
    ]
