# Generated by Django 2.2.5 on 2019-10-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starboardscanner_app', '0004_report_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
    ]
