# Generated by Django 2.2.5 on 2019-10-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starboardscanner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_port',
            field=models.IntegerField(null=True),
        ),
    ]
