# Generated by Django 2.2.5 on 2019-10-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starboardscanner_app', '0003_auto_20191008_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
    ]
